"""add job heartbeats table

Revision ID: 0a1e655c3a1a
Revises: 4e09b0ea2b8f
Create Date: 2026-07-06 20:23:02.814831

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

import sentinel.infrastructure.persistence.types

revision: str = "0a1e655c3a1a"
down_revision: str | None = "4e09b0ea2b8f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "job_heartbeats",
        sa.Column("id", sentinel.infrastructure.persistence.types.GUID(length=36), nullable=False),
        sa.Column("job_id", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("last_run_at", sa.DateTime(), nullable=False),
        sa.Column("last_duration_ms", sa.Float(), nullable=False),
        sa.Column("last_error", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("job_heartbeats", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_job_heartbeats_job_id"), ["job_id"], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("job_heartbeats", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_job_heartbeats_job_id"))

    op.drop_table("job_heartbeats")
    # ### end Alembic commands ###
