"""add quarantine ownership metadata

Revision ID: 35e622664e39
Revises: c24b516cab23
Create Date: 2026-07-07 10:24:44.074840

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "35e622664e39"
down_revision: str | None = "c24b516cab23"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("integrity_findings", schema=None) as batch_op:
        batch_op.add_column(sa.Column("quarantine_owner_uid", sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column("quarantine_owner_gid", sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("integrity_findings", schema=None) as batch_op:
        batch_op.drop_column("quarantine_owner_gid")
        batch_op.drop_column("quarantine_owner_uid")

    # ### end Alembic commands ###
