"""create integrity tables

Revision ID: 39d1adfb086b
Revises: 5183d1a759e4
Create Date: 2026-06-30 03:18:57.809329

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

import sentinel.infrastructure.persistence.types

revision: str = "39d1adfb086b"
down_revision: str | None = "5183d1a759e4"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "file_baselines",
        sa.Column("id", sentinel.infrastructure.persistence.types.GUID(length=36), nullable=False),
        sa.Column(
            "account_id", sentinel.infrastructure.persistence.types.GUID(length=36), nullable=False
        ),
        sa.Column("relative_path", sa.String(length=1024), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("size_bytes", sa.Integer(), nullable=False),
        sa.Column("mode", sa.String(length=4), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("last_verified_at", sa.DateTime(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["account_id"], ["cpanel_accounts.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("account_id", "relative_path"),
    )
    with op.batch_alter_table("file_baselines", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_file_baselines_account_id"), ["account_id"], unique=False
        )

    op.create_table(
        "integrity_findings",
        sa.Column("id", sentinel.infrastructure.persistence.types.GUID(length=36), nullable=False),
        sa.Column(
            "account_id", sentinel.infrastructure.persistence.types.GUID(length=36), nullable=False
        ),
        sa.Column("relative_path", sa.String(length=1024), nullable=False),
        sa.Column("change_type", sa.String(length=32), nullable=False),
        sa.Column("severity", sa.String(length=16), nullable=False),
        sa.Column("previous_sha256", sa.String(length=64), nullable=True),
        sa.Column("current_sha256", sa.String(length=64), nullable=True),
        sa.Column("is_acknowledged", sa.Boolean(), nullable=False),
        sa.Column("detected_at", sa.DateTime(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["account_id"], ["cpanel_accounts.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("integrity_findings", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_integrity_findings_account_id"), ["account_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_integrity_findings_detected_at"), ["detected_at"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("integrity_findings", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_integrity_findings_detected_at"))
        batch_op.drop_index(batch_op.f("ix_integrity_findings_account_id"))

    op.drop_table("integrity_findings")
    with op.batch_alter_table("file_baselines", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_file_baselines_account_id"))

    op.drop_table("file_baselines")
    # ### end Alembic commands ###
