"""add security intelligence engine tables

Revision ID: 4e09b0ea2b8f
Revises: 504b928e5594
Create Date: 2026-07-06 14:37:53.900608

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

import sentinel.infrastructure.persistence.types

revision: str = "4e09b0ea2b8f"
down_revision: str | None = "504b928e5594"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "incidents",
        sa.Column("id", sentinel.infrastructure.persistence.types.GUID(length=36), nullable=False),
        sa.Column("title", sa.String(length=256), nullable=False),
        sa.Column("correlation_signature", sa.String(length=256), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("severity", sa.String(length=16), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("first_seen_at", sa.DateTime(), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(), nullable=False),
        sa.Column("root_cause", sa.Text(), nullable=True),
        sa.Column("recommended_actions", sa.Text(), nullable=True),
        sa.Column("false_positive_probability", sa.Float(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("incidents", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_incidents_correlation_signature"),
            ["correlation_signature"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_incidents_last_seen_at"), ["last_seen_at"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_incidents_status"), ["status"], unique=False)

    op.create_table(
        "incident_account_links",
        sa.Column("id", sentinel.infrastructure.persistence.types.GUID(length=36), nullable=False),
        sa.Column(
            "incident_id", sentinel.infrastructure.persistence.types.GUID(length=36), nullable=False
        ),
        sa.Column(
            "account_id", sentinel.infrastructure.persistence.types.GUID(length=36), nullable=False
        ),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["account_id"], ["cpanel_accounts.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["incident_id"], ["incidents.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("incident_id", "account_id"),
    )
    with op.batch_alter_table("incident_account_links", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_incident_account_links_account_id"), ["account_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_incident_account_links_incident_id"), ["incident_id"], unique=False
        )

    op.create_table(
        "security_events",
        sa.Column("id", sentinel.infrastructure.persistence.types.GUID(length=36), nullable=False),
        sa.Column("event_type", sa.String(length=64), nullable=False),
        sa.Column("source_context", sa.String(length=64), nullable=False),
        sa.Column(
            "account_id", sentinel.infrastructure.persistence.types.GUID(length=36), nullable=True
        ),
        sa.Column("severity", sa.String(length=16), nullable=False),
        sa.Column("payload", sa.Text(), nullable=False),
        sa.Column("occurred_at", sa.DateTime(), nullable=False),
        sa.Column("processed_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["account_id"], ["cpanel_accounts.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("security_events", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_security_events_account_id"), ["account_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_security_events_event_type"), ["event_type"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_security_events_occurred_at"), ["occurred_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_security_events_processed_at"), ["processed_at"], unique=False
        )

    op.create_table(
        "temp_file_observations",
        sa.Column("id", sentinel.infrastructure.persistence.types.GUID(length=36), nullable=False),
        sa.Column("absolute_path", sa.String(length=1024), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=True),
        sa.Column("owner", sa.String(length=64), nullable=False),
        sa.Column("size_bytes", sa.Integer(), nullable=False),
        sa.Column("verdict", sa.String(length=16), nullable=False),
        sa.Column("verdict_reason", sa.String(length=512), nullable=False),
        sa.Column("matched_rule_ids", sa.Text(), nullable=False),
        sa.Column("process_context", sa.Text(), nullable=True),
        sa.Column(
            "account_id", sentinel.infrastructure.persistence.types.GUID(length=36), nullable=True
        ),
        sa.Column("detected_at", sa.DateTime(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["account_id"], ["cpanel_accounts.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("absolute_path"),
    )
    with op.batch_alter_table("temp_file_observations", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_temp_file_observations_account_id"), ["account_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_temp_file_observations_detected_at"), ["detected_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_temp_file_observations_verdict"), ["verdict"], unique=False
        )

    op.create_table(
        "threat_timeline_entries",
        sa.Column("id", sentinel.infrastructure.persistence.types.GUID(length=36), nullable=False),
        sa.Column(
            "incident_id", sentinel.infrastructure.persistence.types.GUID(length=36), nullable=False
        ),
        sa.Column("stage", sa.String(length=64), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("occurred_at", sa.DateTime(), nullable=False),
        sa.Column(
            "source_event_id",
            sentinel.infrastructure.persistence.types.GUID(length=36),
            nullable=True,
        ),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["incident_id"], ["incidents.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["source_event_id"], ["security_events.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("threat_timeline_entries", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_threat_timeline_entries_incident_id"), ["incident_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_threat_timeline_entries_occurred_at"), ["occurred_at"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("threat_timeline_entries", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_threat_timeline_entries_occurred_at"))
        batch_op.drop_index(batch_op.f("ix_threat_timeline_entries_incident_id"))

    op.drop_table("threat_timeline_entries")
    with op.batch_alter_table("temp_file_observations", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_temp_file_observations_verdict"))
        batch_op.drop_index(batch_op.f("ix_temp_file_observations_detected_at"))
        batch_op.drop_index(batch_op.f("ix_temp_file_observations_account_id"))

    op.drop_table("temp_file_observations")
    with op.batch_alter_table("security_events", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_security_events_processed_at"))
        batch_op.drop_index(batch_op.f("ix_security_events_occurred_at"))
        batch_op.drop_index(batch_op.f("ix_security_events_event_type"))
        batch_op.drop_index(batch_op.f("ix_security_events_account_id"))

    op.drop_table("security_events")
    with op.batch_alter_table("incident_account_links", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_incident_account_links_incident_id"))
        batch_op.drop_index(batch_op.f("ix_incident_account_links_account_id"))

    op.drop_table("incident_account_links")
    with op.batch_alter_table("incidents", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_incidents_status"))
        batch_op.drop_index(batch_op.f("ix_incidents_last_seen_at"))
        batch_op.drop_index(batch_op.f("ix_incidents_correlation_signature"))

    op.drop_table("incidents")
    # ### end Alembic commands ###
