"""add remediation actions

Revision ID: 504b928e5594
Revises: db221e4eed0d
Create Date: 2026-07-04 05:39:57.302451

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

import sentinel.infrastructure.persistence.types

revision: str = "504b928e5594"
down_revision: str | None = "db221e4eed0d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "remediation_actions",
        sa.Column("id", sentinel.infrastructure.persistence.types.GUID(length=36), nullable=False),
        sa.Column(
            "finding_id", sentinel.infrastructure.persistence.types.GUID(length=36), nullable=False
        ),
        sa.Column(
            "account_id", sentinel.infrastructure.persistence.types.GUID(length=36), nullable=False
        ),
        sa.Column("relative_path", sa.String(length=1024), nullable=False),
        sa.Column("action_type", sa.String(length=16), nullable=False),
        sa.Column("outcome", sa.String(length=16), nullable=False),
        sa.Column("detail", sa.String(length=1024), nullable=True),
        sa.Column("performed_at", sa.DateTime(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["account_id"], ["cpanel_accounts.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["finding_id"], ["integrity_findings.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("remediation_actions", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_remediation_actions_account_id"), ["account_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_remediation_actions_finding_id"), ["finding_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_remediation_actions_performed_at"), ["performed_at"], unique=False
        )

    with op.batch_alter_table("integrity_findings", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "remediation_state", sa.String(length=16), nullable=False, server_default="NONE"
            )
        )
        batch_op.add_column(sa.Column("quarantine_path", sa.String(length=1024), nullable=True))
        batch_op.add_column(sa.Column("quarantine_mode", sa.String(length=4), nullable=True))
        batch_op.add_column(sa.Column("quarantine_size_bytes", sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("integrity_findings", schema=None) as batch_op:
        batch_op.drop_column("quarantine_size_bytes")
        batch_op.drop_column("quarantine_mode")
        batch_op.drop_column("quarantine_path")
        batch_op.drop_column("remediation_state")

    with op.batch_alter_table("remediation_actions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_remediation_actions_performed_at"))
        batch_op.drop_index(batch_op.f("ix_remediation_actions_finding_id"))
        batch_op.drop_index(batch_op.f("ix_remediation_actions_account_id"))

    op.drop_table("remediation_actions")
    # ### end Alembic commands ###
