"""create discovery tables

Revision ID: 5183d1a759e4
Revises: b344d91fb4a6
Create Date: 2026-06-30 02:51:08.728714

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

import sentinel.infrastructure.persistence.types

revision: str = "5183d1a759e4"
down_revision: str | None = "b344d91fb4a6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "servers",
        sa.Column("id", sentinel.infrastructure.persistence.types.GUID(length=36), nullable=False),
        sa.Column("hostname", sa.String(length=255), nullable=False),
        sa.Column("os_info", sa.String(length=255), nullable=False),
        sa.Column("agent_version", sa.String(length=32), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("servers", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_servers_hostname"), ["hostname"], unique=True)

    op.create_table(
        "cpanel_accounts",
        sa.Column("id", sentinel.infrastructure.persistence.types.GUID(length=36), nullable=False),
        sa.Column(
            "server_id", sentinel.infrastructure.persistence.types.GUID(length=36), nullable=False
        ),
        sa.Column("username", sa.String(length=16), nullable=False),
        sa.Column("primary_domain", sa.String(length=255), nullable=False),
        sa.Column("home_directory", sa.String(length=1024), nullable=False),
        sa.Column("is_suspended", sa.Boolean(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["server_id"], ["servers.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("cpanel_accounts", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_cpanel_accounts_server_id"), ["server_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_cpanel_accounts_username"), ["username"], unique=True)

    op.create_table(
        "wp_installations",
        sa.Column("id", sentinel.infrastructure.persistence.types.GUID(length=36), nullable=False),
        sa.Column(
            "cpanel_account_id",
            sentinel.infrastructure.persistence.types.GUID(length=36),
            nullable=False,
        ),
        sa.Column("absolute_path", sa.String(length=1024), nullable=False),
        sa.Column("domain", sa.String(length=255), nullable=True),
        sa.Column("wp_version", sa.String(length=32), nullable=True),
        sa.Column("is_multisite", sa.Boolean(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["cpanel_account_id"], ["cpanel_accounts.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("wp_installations", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_wp_installations_absolute_path"), ["absolute_path"], unique=True
        )
        batch_op.create_index(
            batch_op.f("ix_wp_installations_cpanel_account_id"), ["cpanel_account_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("wp_installations", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_wp_installations_cpanel_account_id"))
        batch_op.drop_index(batch_op.f("ix_wp_installations_absolute_path"))

    op.drop_table("wp_installations")
    with op.batch_alter_table("cpanel_accounts", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_cpanel_accounts_username"))
        batch_op.drop_index(batch_op.f("ix_cpanel_accounts_server_id"))

    op.drop_table("cpanel_accounts")
    with op.batch_alter_table("servers", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_servers_hostname"))

    op.drop_table("servers")
    # ### end Alembic commands ###
