"""create inventory tables

Revision ID: 5538610004bd
Revises: 39d1adfb086b
Create Date: 2026-07-01 03:09:53.094369

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

import sentinel.infrastructure.persistence.types

revision: str = "5538610004bd"
down_revision: str | None = "39d1adfb086b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "installed_plugins",
        sa.Column("id", sentinel.infrastructure.persistence.types.GUID(length=36), nullable=False),
        sa.Column(
            "installation_id",
            sentinel.infrastructure.persistence.types.GUID(length=36),
            nullable=False,
        ),
        sa.Column("slug", sa.String(length=128), nullable=False),
        sa.Column("name", sa.String(length=256), nullable=False),
        sa.Column("version", sa.String(length=64), nullable=True),
        sa.Column("is_present", sa.Boolean(), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["installation_id"], ["wp_installations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("installation_id", "slug"),
    )
    with op.batch_alter_table("installed_plugins", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_installed_plugins_installation_id"), ["installation_id"], unique=False
        )

    op.create_table(
        "installed_themes",
        sa.Column("id", sentinel.infrastructure.persistence.types.GUID(length=36), nullable=False),
        sa.Column(
            "installation_id",
            sentinel.infrastructure.persistence.types.GUID(length=36),
            nullable=False,
        ),
        sa.Column("slug", sa.String(length=128), nullable=False),
        sa.Column("name", sa.String(length=256), nullable=False),
        sa.Column("version", sa.String(length=64), nullable=True),
        sa.Column("is_present", sa.Boolean(), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["installation_id"], ["wp_installations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("installation_id", "slug"),
    )
    with op.batch_alter_table("installed_themes", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_installed_themes_installation_id"), ["installation_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("installed_themes", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_installed_themes_installation_id"))

    op.drop_table("installed_themes")
    with op.batch_alter_table("installed_plugins", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_installed_plugins_installation_id"))

    op.drop_table("installed_plugins")
    # ### end Alembic commands ###
