"""add forensic metadata to security events and temp file observations

Revision ID: 680ad7c94328
Revises: 0a1e655c3a1a
Create Date: 2026-07-06 20:48:34.703133

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

import sentinel.infrastructure.persistence.types

revision: str = "680ad7c94328"
down_revision: str | None = "0a1e655c3a1a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("security_events", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "server_id",
                sentinel.infrastructure.persistence.types.GUID(length=36),
                nullable=True,
            )
        )
        batch_op.add_column(sa.Column("file_path", sa.String(length=1024), nullable=True))
        batch_op.add_column(sa.Column("sha256", sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column("file_size_bytes", sa.BigInteger(), nullable=True))
        batch_op.add_column(sa.Column("file_owner", sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column("file_permissions", sa.String(length=8), nullable=True))
        batch_op.add_column(sa.Column("mime_type", sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column("scanner_version", sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column("detection_rule_id", sa.String(length=256), nullable=True))
        batch_op.create_index(
            batch_op.f("ix_security_events_server_id"), ["server_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_security_events_sha256"), ["sha256"], unique=False)
        batch_op.create_foreign_key(
            "fk_security_events_server_id_servers",
            "servers",
            ["server_id"],
            ["id"],
            ondelete="CASCADE",
        )

    with op.batch_alter_table("temp_file_observations", schema=None) as batch_op:
        batch_op.add_column(sa.Column("file_permissions", sa.String(length=8), nullable=True))
        batch_op.add_column(sa.Column("mime_type", sa.String(length=128), nullable=True))
        batch_op.add_column(
            sa.Column(
                "server_id",
                sentinel.infrastructure.persistence.types.GUID(length=36),
                nullable=True,
            )
        )
        batch_op.create_index(
            batch_op.f("ix_temp_file_observations_server_id"), ["server_id"], unique=False
        )
        batch_op.create_foreign_key(
            "fk_temp_file_observations_server_id_servers",
            "servers",
            ["server_id"],
            ["id"],
            ondelete="CASCADE",
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("temp_file_observations", schema=None) as batch_op:
        batch_op.drop_constraint("fk_temp_file_observations_server_id_servers", type_="foreignkey")
        batch_op.drop_index(batch_op.f("ix_temp_file_observations_server_id"))
        batch_op.drop_column("server_id")
        batch_op.drop_column("mime_type")
        batch_op.drop_column("file_permissions")

    with op.batch_alter_table("security_events", schema=None) as batch_op:
        batch_op.drop_constraint("fk_security_events_server_id_servers", type_="foreignkey")
        batch_op.drop_index(batch_op.f("ix_security_events_sha256"))
        batch_op.drop_index(batch_op.f("ix_security_events_server_id"))
        batch_op.drop_column("detection_rule_id")
        batch_op.drop_column("scanner_version")
        batch_op.drop_column("mime_type")
        batch_op.drop_column("file_permissions")
        batch_op.drop_column("file_owner")
        batch_op.drop_column("file_size_bytes")
        batch_op.drop_column("sha256")
        batch_op.drop_column("file_path")
        batch_op.drop_column("server_id")

    # ### end Alembic commands ###
