"""add wordpress security engine tables

Revision ID: c24b516cab23
Revises: 680ad7c94328
Create Date: 2026-07-06 22:49:17.739043

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

import sentinel.infrastructure.persistence.types

revision: str = "c24b516cab23"
down_revision: str | None = "680ad7c94328"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "wordpress_core_checksums",
        sa.Column("id", sentinel.infrastructure.persistence.types.GUID(length=36), nullable=False),
        sa.Column("wp_version", sa.String(length=32), nullable=False),
        sa.Column("relative_path", sa.String(length=512), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("fetched_at", sa.DateTime(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("wp_version", "relative_path"),
    )
    with op.batch_alter_table("wordpress_core_checksums", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_wordpress_core_checksums_wp_version"), ["wp_version"], unique=False
        )

    op.create_table(
        "wordpress_cron_jobs",
        sa.Column("id", sentinel.infrastructure.persistence.types.GUID(length=36), nullable=False),
        sa.Column(
            "installation_id",
            sentinel.infrastructure.persistence.types.GUID(length=36),
            nullable=False,
        ),
        sa.Column("command", sa.Text(), nullable=False),
        sa.Column("schedule_raw", sa.String(length=128), nullable=False),
        sa.Column("is_suspicious", sa.Boolean(), nullable=False),
        sa.Column("flag_reason", sa.String(length=256), nullable=True),
        sa.Column("is_present", sa.Boolean(), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["installation_id"], ["wp_installations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("wordpress_cron_jobs", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_wordpress_cron_jobs_installation_id"),
            ["installation_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_wordpress_cron_jobs_is_suspicious"), ["is_suspicious"], unique=False
        )

    with op.batch_alter_table("wp_installations", schema=None) as batch_op:
        batch_op.add_column(sa.Column("php_version", sa.String(length=16), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("wp_installations", schema=None) as batch_op:
        batch_op.drop_column("php_version")

    with op.batch_alter_table("wordpress_cron_jobs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_wordpress_cron_jobs_is_suspicious"))
        batch_op.drop_index(batch_op.f("ix_wordpress_cron_jobs_installation_id"))

    op.drop_table("wordpress_cron_jobs")
    with op.batch_alter_table("wordpress_core_checksums", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_wordpress_core_checksums_wp_version"))

    op.drop_table("wordpress_core_checksums")
    # ### end Alembic commands ###
