"""create configuration items table

Revision ID: db221e4eed0d
Revises: 5538610004bd
Create Date: 2026-07-01 03:38:55.994084

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

import sentinel.infrastructure.persistence.types

revision: str = "db221e4eed0d"
down_revision: str | None = "5538610004bd"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "configuration_items",
        sa.Column("id", sentinel.infrastructure.persistence.types.GUID(length=36), nullable=False),
        sa.Column(
            "installation_id",
            sentinel.infrastructure.persistence.types.GUID(length=36),
            nullable=False,
        ),
        sa.Column("config_source", sa.String(length=128), nullable=False),
        sa.Column("key", sa.String(length=128), nullable=False),
        sa.Column("raw_value", sa.Text(), nullable=True),
        sa.Column("is_flagged", sa.Boolean(), nullable=False),
        sa.Column("flag_reason", sa.String(length=512), nullable=True),
        sa.Column("is_present", sa.Boolean(), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["installation_id"], ["wp_installations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("installation_id", "config_source", "key"),
    )
    with op.batch_alter_table("configuration_items", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_configuration_items_installation_id"), ["installation_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("configuration_items", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_configuration_items_installation_id"))

    op.drop_table("configuration_items")
    # ### end Alembic commands ###
